// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:workspace/models/pet.dart';
import 'package:workspace/models/settings.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(PetAdapter());
    registerAdapter(SettingsAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(PetAdapter());
    registerAdapter(SettingsAdapter());
  }
}
